image: maven:latest

stages:
  - build
  - test
  - code-quality

build:
  stage: build
  script:
    - cd happy-tummy-backend
    - mvn install

test:
  stage: test
  script:
    - cd happy-tummy-backend
    - mvn test

smells-job:
    stage: code-quality
    image: openjdk:11
    script:
        - echo "Starting DesigniteJava"
        - mkdir smells/
        - java -jar $CI_PROJECT_DIR/.gitlab/DesigniteJava.jar -i $CI_PROJECT_DIR/happy-tummy-backend -o smells/ -d
        - cd smells/
        - ls -a
    artifacts:
      paths:
        - smells/
        - $CI_PROJECT_DIR

