def projectName = ""
def branchName1 = "asdasd"
def branchName2 = "master"
def dirName = "${projectName}"
def osUser = "ubuntu"
def ipAddr = ""
def agentName = ""

pipeline {
    options {
        buildDiscarder(logRotator(numToKeepStr: "7"))
    }
    agent {
        docker { image 'node:14.15.0' }
    }
    environment {
        HOME = '.'
    }
    stages {
        stage("Build")
        {
            steps
            {
                dir('HappyTummyFrontend') {
                    sh "npm cache clean --force"
                    sh "npm install"
                    sh "npm install @angular/cli"
                    sh "npm run build"
                }
            }
        }

        stage("Deploy")
        {
            steps
            {
                script {
                    if (env.BRANCH_NAME == "${branchName2}")
                    {
                        echo "Deleting the old build.  "
                        sh "rm -r /var/www/html || ls"
                        echo "Old build deleted, Deploying new build"
                        sh "cp -a /home/csci5308vm6/group06/HappyTummyFrontend/dist/happy-tummy-frontend/. /var/www/html"
                        echo "Build Deployed. "
                    }
                }
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}