pipeline {
    options {
        buildDiscarder(logRotator(numToKeepStr: '7'))
    }
    agent any
    environment {
        HOME = '.'
    }
    stages {
        stage('Build')
        {
            steps
            {
                script {
                    echo "${env.GIT_BRANCH}"
                    sh 'printenv'
                    dir('HappyTummyFrontend') {
                        sh 'npm cache clean --force'
                        sh 'npm install'
                        sh 'npm install @angular/cli'
                        if (${env.GIT_BRANCH} == 'origin/master') {
                            sh 'npm run build -- --prod --base-href /'
                        }
                        else {
                            sh "npm run build -- --prod --base-href /${env.GIT_BRANCH.split('/')[1]}/"
                        }
                    }
                }
            }
        }
        stage('Deploy')
        {
            steps
            {
                script {
                    dir('HappyTummyFrontend') {
                        if (${env.GIT_BRANCH} == 'origin/master') {
                            echo 'Deleting the old build.  '
                            sh 'rm -r /var/www/html || ls'
                            echo 'Old build deleted, Deploying new build'
                            sh 'cp -a dist/happy-tummy-frontend/. /var/www/html'
                            echo 'Build Deployed. '
                        }else {
                            echo 'Deleting the old build.  '
                            sh "rm -r /var/www/html/${env.GIT_BRANCH.split('/')[1]} || ls"
                            echo 'Old build deleted, Deploying new build'
                            sh "cp -a dist/happy-tummy-frontend/. /var/www/html/${env.GIT_BRANCH.split('/')[1]}"
                            echo 'Build Deployed. '
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
